version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres_prac
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: prac
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
